### ISSUE TITLE
Customizable X11 window ID / Class

### ISSUE THREAD

**Issue by derf** [derf/feh#180]
Adding an option for a custom window ID / window class might be helpful to help a window manager distinguish between special feh instances.

**Comment by marak8** [comment]
One use case. I'd like to create a program that'll popup QR code of current content in clipboard. The script is quite simple:

    xsel | qrencode -o - | feh -x -

In tiling managers like i3, I'd like this popup to be floating, while for browsing photos, I'd like the feh to be standard window in split tree. For this, a customizable X11 class would be required. As a workaround I can match against window title, which I can set with feh (I think).

**Comment by vitotafuni** [comment]
up!

Still a usefull feature after 5 years!
When using with xscreensaver to show a custom slideshow (no need for random images screensavers) no images is shown because writing on the root window.

xscreensaver can pass a useful parameter XSCREENSAVER_WINDOW that mplayer and xloadimage already use to work the right way.

**Comment by Ferada** [comment]
@vitotafuni does https://github.com/derf/feh/pull/425 that work for you?

**Comment by derf** [comment]
Hi! I just merged #425, sorry for the long delay. As @Ferada says: Please let us know if that works for you

**Comment by codehearts** [comment]
I'm trying to use `feh` with `xsecurelock`, which I guess is a similar use case to `xscreensaver` because the image has to be drawn to `$XSCREENSAVER_WINDOW`. I don't think it's possible to use the window class for this, it has to be drawn using the window id.

I was peeking at [how this `xloadimage` fork(?) does this](https://github.com/OS2World/APP-GRAPHICS-X11-XLOADIMAGE/blob/ae0e57c8f6928765bee50fd451743cc2195bad6e/root.c#L156) and might try to implement that here since `xloadimage` doesn't support the kind of zooming that `feh` does and it's driving me batty.

My C is rusty (from writing Rust nowadays, ironically), but it looks like `xloadimage`'s handful of lines to determine the parent window will provide a value that can be passed to the existing `XSetWindowBackgroundPixmap` calls in `feh`.
