### ISSUE TITLE
Randomize doesn’t work any more

### ISSUE THREAD

**Issue by Elfram** [derf/feh#199]
Since an update from version 2.12.1-1 to 2.13.1-1 (Debian testing) every call of feh with `--randomize` outputs

     feh WARNING: You cant sort AND randomize the filelist...
     randomize mode has been unset

**Comment by hidroto** [comment]
are you sure you are not using the --sort option because if you are then 
this is a feature and not a bug.

can you give the full command line that shows the problem.

**Comment by Elfram** [comment]
Of course. Before the update it worked normally. The command I use is `feh --bg-fill --no-xinerama --recursive --randomize ~/dir/` but it happens for commands as simple as `feh --randomize ~/dir/`.

**Comment by derf** [comment]
I cannot reproduce that here. What is the content of your `~/.config/feh/themes`?

**Comment by Elfram** [comment]
Thanks for your hint. My feh theme contained a sort option. I created another theme without and it worked like a charm. :-) Sorry for bothering…

For  the sake of completeness: Is it possible to disable sorting explicitly (i.e. -S none)?

**Comment by derf** [comment]
It would be trivial to add, but not exactly true to its name: When no sort option is specified, feh still sorts files by name due to the scandir implementation it uses (and I don't want to change that).

I think the most sensible thing to do here is change the behaviour of that warning, so that the last option overrides the previous one instead of --sort always overriding --randomize. This way, you can use a theme specifying --sort as usual and override it by specifying --randomize on the commandline (which works fine since commandline options always override theme options).

I'll leave the warning itself in though, just to avoid confusion.
