### ISSUE TITLE
Segmentation fault --bg-scale

### ISSUE THREAD

**Issue by xPhentom** [derf/feh#215]
So I suddenly can't set my wallpaper on i3 anymore. Feh is giving me an error: Segmentation fault

**Comment by derf** [comment]
Could you give me a backtrace? If possible, rebuild feh with `make debug=1`,
then run `gdb --args src/feh --bg-foo bar quux`, type `run` and wait for it to
crash, then type `bt` and give me the output.

**Comment by xPhentom** [comment]
I'm pretty much a noob in this stuff, could you explain some more?

**Comment by xPhentom** [comment]
Re-installed everything, yet I'm still getting this error after two days

**Comment by derf** [comment]
What's the output of `feh --version`?

Regarding the backtrace: I need to know which functions led to your segmentation fault, and for that I need a backtrace (and a feh debug build, cause otherwise it's usually not very helpful). So what I need you to do is, if possible:

* get the feh source (e.g. by cloning this repository)
* Install the dependencies and compile it (see https://feh.finalrewind.org/ "Building from source"), but use "make debug=1" instead of "make" --- there's no need for "make install" in this case
* after running "make debug=1", run "gdb --args src/feh --whatever args you use for background setting" (probably feh --bg-fill somefile.jpg). Install gdb first if neccessary
* gdb will start a shell of its own. type "run" in there to start feh itself
* as soon as it crashes, gdb will notify you. type "bt" and give me the lines it prints after that.

**Comment by xPhentom** [comment]
Alright, I'll get to it as soon as possible. For the question about which version I have, it gives me "Segmentation fault" as output

**Comment by derf** [comment]
oh, so something's _really_ broken there :)

in that case you can also use "gdb --args src/feh --version" I guess, the rest remains the same though.

**Comment by xPhentom** [comment]
Apparently I also have this problem with wget, any chance this info helps you?

**Comment by derf** [comment]
If some other programs on your system also immediately run into a segmentation fault, there's a high chance that feh is not the culprit here, yeah. Creating a backtrace still helps though, with that there's a chance you'll at least know what's wrong and where it's going wrong.

**Comment by derf** [comment]
Closing this (no new replies, pretty sure it isn't feh-specific)
