### ISSUE TITLE
feh renders stripe when the image is small

### ISSUE THREAD

**Issue by acgtyrant** [derf/feh#219]
I open a image which is 30x30, then feh show extra stripe:

![1453430241](https://cloud.githubusercontent.com/assets/3921062/12501073/3aa9fcc8-c0f4-11e5-85ec-dc9dbdd9ee68.png)

I do not want that stripe, only the origin image! Thank you!

**Comment by derf** [comment]
feh shouldn't do that and I can't reproduce it here. Please give me some more information so I can track down what's happening:

* The output of ` feh --version`
* The content of your `~/.config/feh/themes` (if present)
* The name of your window manager

**Comment by acgtyrant** [comment]
* `feh --version`:

	feh version 2.14
	Compile-time switches: curl exif help stat64 xinerama

* no `~/.config/feh/themes`.
* i3.

**Comment by derf** [comment]
Ah, then that's i3 doing stuff. According to <https://i3wm.org/docs/userguide.html#_constraining_floating_window_size> it enforces a minimum window size by default, so if the image is smaller there's nothin feh can do about it. You need to change your i3 config to fix that.

Though for the time being, you can also use `feh -B black ...` to get a solid black background instead of the checkboard pattern, if that helps.

**Comment by acgtyrant** [comment]
Thank you!
