### ISSUE TITLE
Any way to make left click run a script?

### ISSUE THREAD

**Issue by Lew-Rockwell-Fan** [derf/feh#240]
Is there any way to make the left mouse button run a script? I thougt at first it would be in the buttons config file but the way I'm reading that, all I can put there is predefined actions. Then I thought maybe I could use openbox's rc file, but I haven't figured out how to limit the remapping to feh. Now I'm beginning to wonder if I'm going to have to use something like xdotool to make feh see the click as a numeral key. Can anybody point me in a promising direction?

Thanks.

**Comment by derf** [comment]
Mouse buttons can not yet run actions, though you can add https://github.com/derf/feh/pull/220 to your feh build as a workaround.

I plan to merge key and mouse configs so that mouse buttons can do anything you can bind a key to, but the only ETA I have for that is "some unspecified point in the future"

**Comment by derf** [comment]
As of 75e1e83713a83cd98f05d35efcedd6ac041788da, key events (such as actions) can also be mapped to buttons, so you can make left click run action0, action1 or similar and specify the script to run using --action. This feature will be included in the next release.

**Comment by Lew-Rockwell-Fan** [comment]
Cool! THanks.
