### ISSUE TITLE
emacs 'WoMan' manpage formatter can't render feh manpage

### ISSUE THREAD

**Issue by alive4ever** [derf/feh#249]
Emacs has an alternative manpage viewer, codenamed 'WoMan'.

Attempting to view feh manpage in emacs with 'WoMan' (`M-x woman <ret> feh <ret>`) causes feh manpage to render incorrectly and error message.
```
feh man page formatted
uncompressing feh.1.gz...done
WoMan formatting buffer...
woman-decode-region: WoMan can only format man pages written with the usual `-man' macros
```

**Comment by derf** [comment]
Hi,

Yeah, the feh manual is written in `mandoc` (not `roff`based macros), but WoMan only supports `roff`/`nroff` based manpages. I think this is a WoMan rather than a feh issue, which just rarely surfaces because most Linux manpages are written in `nroff`, while `mandoc` can mostly be seen on BSD systems.
