### ISSUE TITLE
Randomize don't work well with large amount of files

### ISSUE THREAD

**Issue by A-Kamf** [derf/feh#284]
When sending a large list of files to feh, it seems to divide the slideshow in chunks of about 1000 files each and do the randmization within each chunk instead of the whole list of files. 
My list of files is sorted according to date. Hence, when I like a random slideshow of pictures dating from 2010 until now (about 15000 files), feh starts with random pictures only from 2010 and some from 2011. Then I will see the rest from 2011 and some from 2012 and so on.

I’ll guess a main question is: how come feh divides the files to show in chunks of about 1000 pictures? 

My feh version is 2.14. 
My command to launch feh:
less filelist.txt | xargs feh --auto-zoom -F -Y -D 7 -Z -V --auto-rotate --info "exiftool -DateTimeOriginal -Keywords -Rating -s -s -s %F"

**Comment by derf** [comment]
Hi,

I created a directory with 10000 images and added the -z / --randomize option to the command you pasted above. However, I was not able to reproduce it, neither in 2.14 nor in the current git HEAD. Please provide more details.

**Comment by derf** [comment]
Someone else just suggested that the issue is, in fact, not feh but xargs. Depending on the filename length and your system configuration, xargs will split the file list into multiple feh invocations. so, feh is not able to randomize the entire filelist because xargs doesn't supply it.

Solution: Use feh -f filelist.txt ...

**Comment by A-Kamf** [comment]
Thanks, that probably explains it!
