### ISSUE TITLE
Play gifs

### ISSUE THREAD

**Issue by vktec** [derf/feh#308]
It'd be nice if feh could play gifs. It should probably only do so in slideshow and multiwindow mode, as it might get distracting in montage or index.

When the slideshow is paused, the gif could loop with an option to pause. When playing, either the gif could play once and then move on to the next image, loop until the delay is over and then move on immediately, or loop until the delay is over, finish that loop and then move on.

Perhaps there could also be a "one-shot" mode where animations just loop once and then either stay at the last frame or go back to the first one (whichever's easiest).

**Comment by Nopey** [comment]
im2lib may or may not support animated GIFs, I havn't checked.
im2lib supports GIF through GIFLIB, which definitely supports animated GIFs.
Is there a mailing list for im2lib, or some other place for im2lib discussion?
the "one-shot" feature you are speaking about is already a feature available to the creator of the GIF, but thats a moot point.

**Comment by vktec** [comment]
From a quick search of imlib2's API docs, I can't see anything referencing animation, but that's certainly not conclusive evidence.

If imlib2 _doesn't_ support animation, perhaps giflib could be used directly?

**Comment by derf** [comment]
Sorry to reject this, but feh is an image viewer and not a movie / gif player. mplayer/mpv already do a pretty good job at that, and apart from that I'm also not willing to invest the (considerable) amount of work required for animation support in feh.

Depending on how urgently you need it / how important it is to play gifs in feh instead of another software, you may be able to use a workaround: Use ImageMagick to convert gifs to one picture for each frame, then use feh --slideshow-delay _some small value_ to play the animation.

**Comment by vktec** [comment]
Okay, that's fair enough. Thanks for keeping feh minimal :)
