### ISSUE TITLE
Question: Click On Images In Directory And Scroll?

### ISSUE THREAD

**Issue by ghost** [derf/feh#372]
Hi,

If I click on an image in a directory of images, does Feh then have the ability to scroll through images in that directory? I'm not really seeing this, so if this is not an option, maybe in the future feh can be created to do this?

Like click an image in your file manger, feh window opens showing image, and then with the mousewheel you scroll back and forth through images in a directory.

Thanks

**Comment by ulteq** [comment]
That's the default behavior of feh.

**Comment by Geyup** [comment]
Doesn't do anything here...

mousewheel, left click, right click, keyboard keys, nothing works to scroll through a directory of images...

All I get is a menu when right clicking...

**Comment by ulteq** [comment]
Feh will only load a single image when you double click onto a file. You need to either select multiple files or use the command line.

**Comment by Geyup** [comment]
Ok, maybe in the future Daniel can make it so you can click an image and scroll through them, this would be nice...

Thanks

**Comment by ulteq** [comment]
Try the `--start-at` option. It might do exactly what you want, depending on how your file manager is calling feh.

**Comment by derf** [comment]
Hmm, I think I can change feh's default behaviour so that `feh --start-at ~/Pictures/whatever.jpg` behaves as if you had called `feh --start-at ~/Pictures/whatever.jpg ~/Pictures`. That way, it's possible to use `--start-at` in feh's XDG application file and get the desired behaviour.

There might be some edge cases though, so I'll come back to this later, hopefully with a working implementation (and hopefully in the not-so-distant future)

**Comment by derf** [comment]
With the latest git version, you can change your feh.desktop to `Exec=feh --start-at %f`. This will cause feh to display the file you clicked on and allow navigation inside the corresponding directory using the next/prev keys.
