### ISSUE TITLE
Can you proportionally resize images?

### ISSUE THREAD

**Issue by catzybluphish** [derf/feh#436]
Like in Adobe Photoshop where you would hold shift while resizing it so it doesn't stretch to distort the image, it remains in its original resolution. Although feh doesn't break the resolution, it creates these grey checkered patterns in the area if it were to stretch out. Is there an option to not stretch the window size of feh and force it to remain in the original resolution? Using bspwm.
Cheers.

**Comment by derf** [comment]
Assuming I understand your issue correctly:

bspwm appears to be a tiling window manager, so by default, it will force feh to use a certain window size and feh will react by drawing checkered patterns in non-image areas (since the enforced window size rarely has the same aspect ratio as the image).

This is by design – if you want to avoid fixed window sizes for feh, you can probably tell your bspwm instance to run it in floating mode (or similar) instead.

Or you can use `--image-bg black` to have a less obtrusive black background instead of the default checkerboard pattern.

If that's not the issue, could you please give some more details of expected and observed behaviour so I can try to reproduce it?

**Comment by catzybluphish** [comment]
Yeah, I'm currently making feh open in floating mode so the window is resized to the image resolution, not for it to take up the entire half of the screen. It's when you manually resize the floating window of feh with your mouse but because of hand inaccuracy, you can stretch the window dimensions either higher or wider than the original image (the image stays the same which is good) which reveals the checkered pattern or black color you suggested. Just wanted to know if there was a way to force the window dimensions to stay the same when resizing as the image's dimensions because sometimes when I want to enlarge an image, I'll spend some considerable time making sure the feh window is perfectly aligned with the image so no checkered patterns are visible.

Hope that was clearer. There's really nothing to reproduce. Anyway, just a small idea.

https://d2x3xhvgiqkx42.cloudfront.net/12345678-1234-1234-1234-1234567890ab/2016/03/27/4c0c6b29-5ba2-4753-8983-7689a267da97.gif
^This is exactly what I want.

**Comment by ulteq** [comment]
Can't you just zoom into the image, then press `w` to fit the window dimensions to the new image size?

**Comment by catzybluphish** [comment]
> Can't you just zoom into the image, then press `w` to fit the window dimensions to the new image size?

Thanks, that was exactly what I looking for.

**Comment by Shellcat-Zero** [comment]
I know this is an old post, but is there no way to tell feh to just open the image to fit it's window space rather than tiling to fit that space? This was the behavior I expected from the `--scale-down` option from the feh man page:
```
     -., --scale-down
             Scale images to fit window geometry (defaults to screen size when no geometry was specified).  Note that the window geometry is not updated when changing images at the moment.  This option is recommended for tiling win‐
             dow managers.  This option is ignored when in fullscreen and thumbnail list mode.

             In tiling environments, this also causes the image to be centered in the window.
```
That seems to be the default behavior of [sxiv](https://github.com/muennich/sxiv) when opening images.
