### ISSUE TITLE
Pictures not saved when rotating

### ISSUE THREAD

**Issue by ewtaylo** [derf/feh#438]
I am running feh on a raspberry pi.  I have everything set up and am starting feh using:
feh -zrFYqZxD15 /home/pi/pictures

When I press the < or > to rotate the pictures in the slide show the program immediately does the rotation and shows the rotated image.  My problem is that the next time the picture is shown it is still in the original orientation.

I have tried setting the picture permissions to 777 and that did not help.  Do you have any ideas that I can look at to get the pictures to save after I have explicitly hit the button to do the rotation?  All the documentation I have seen on the internet indicates that the image should be saved after the button push.

**Comment by Ferada** [comment]
The default changed from applying modifications immediately to not doing that in release 3.0, https://github.com/derf/feh/blob/master/ChangeLog#L39.

**Comment by ewtaylo** [comment]
wow.  I am sorry I can't read.  Thank you for your help.  It was driving me crazy.  I am not a strong linux person so I thought it was something in the way I had put together the Rpi.

**Comment by derf** [comment]
Well, the online manuals for 2.x (which, as pointed out, did have different behaviour) certainly didn't help minimize the confusion :)

I made that change because most feh users don't expect the < / > keys to permanently rotate images on the disk. I'm afraid a little bit of confusion during the transition period is unavoidable, so I'm glad you got it sorted out so quickly.
