### ISSUE TITLE
scrolling leads to worse quality

### ISSUE THREAD

**Issue by blawiz** [derf/feh#476]
Eg scroll_up with ctrl-up, distort image somewhat (easily seen in text images), scroll_up_page with ctrl-pgup doesn't lead to the same problem, zooming in/out fixes it again.

**Comment by derf** [comment]
That's by design – feh does not perform antialiasing after small scrollsteps when using keyboard input, as I expect users to perform them several times in fast succession until they have reached their desired position and antialiasing would slow that process down quite a bit.

Please press "R" (the "render" key) after scrolling to get back to proper image quality.
