### ISSUE TITLE
"No Imlib2 loader for that file format" for gif picture on RaspberryPI / OS 32bits after upgrade to Debian 11 

### ISSUE THREAD

**Issue by UgoPoddine** [derf/feh#630]
Hello,

after having upgraded the PI/OS 32bits system to Debian 11 and re-installed FEH from repository (version 3.6.3-1), I'm start getting getting "No Imlib2 loader for that file format" error when opening gif pictures with :

feh --reload 150 https://iono.jpl.nasa.gov/RT/latest_rti.gif

I have also installed FEH from source, but this not solves the issue.

Thank-you
Best regards
Ugo

**Comment by derf** [comment]
This is caused by an unfortunate combination of library behaviours.

* feh downloads the picture to /tmp/feh_..._latest_rti.gif_XXXXXX (with XXXXXX being random)
* Imlib2 only loads gif images if the file suffix is .gif
* feh cannot place the random XXXXXX part elsewhere, as the library function (mkstemp) it uses for that doesn't support it

I might be able to resort to mkstemps on architectures which support it.

**Comment by derf** [comment]
See #621 for the Imlib2 side of things

**Comment by derf** [comment]
The next Imlib2 release will include a fix: https://git.enlightenment.org/legacy/imlib2.git/commit/?id=43f82f3bc80324282ec22cb6b7c0e0b3ca2b663f

Unfortunately, it likely won't end up in Debian 11

**Comment by UgoPoddine** [comment]
Thank-you Daniel.
I will install from git.
In any case your workaround works well.

Ugo

Il giorno 14 set 2021, 23:15, alle ore 23:15, Daniel Friesel ***@***.***> ha scritto:
