### ISSUE TITLE
Wrong orientation with exif=1 --auto-rotate with imlib 1.7.5

### ISSUE THREAD

**Issue by xjanu** [derf/feh#642]
Since upgrading to imlib2 version 1.7.5 feh rotates images with exif orientation data twice.
With my quick testing it seems that imlib2 has started rotating the image by itself, so when feh checks the exif data, it rotates the image again, resulting in incorrect orientation.

This issue does not seem to happen with imlib2 1.7.4

**Comment by xjanu** [comment]
I've read the imlib2-1.7.5 Changelog and confirm that it started handling orientation  based on EXIF data.

The best fix would probably be just to deprecate the --auto-rotate flag and disable the orientation code for imlib2-1.7.5+ but I don't know if that can be done since the imlib2 has no internal mechanism for checking the loaded lib version.

**Comment by derf** [comment]
Indeed. At least Imlib2 1.7.5 introduces version macros in Imlib2.h, so we can check at compile time. For now, I'll update the documentation and see if I can find another method to automatically enable/disable auto-rotate at runtime.

**Comment by derf** [comment]
I have inserted a compile-time check which disables --auto-rotate (and prints a warning instead) in feh builds compiled with Imlib2 v1.7.5 or later. Could you verify that it works (and orients images) as intended on your system?

**Comment by xjanu** [comment]
Yes, it works exactly as described. Thanks and enjoy the holidays!

**Comment by denarced** [comment]
This is definitely a niche use case but I'll mention it anyway in case it's relevant or slightly amusing. I have intentionally not used --auto-rotate because going through thousands of sports photos is faster that way when using a battery powered laptop: no time wasted for rotating. I also shoot volleyball a lot so most of the photos are vertical so I just rotate the laptop in my hand and then I can go through even 4,000 photos / hour. That way I can also fill the entire screen with the photos so it's easier to see when photos are not perfectly in focus. But who knows, maybe rotation is faster now since it'll happen completely in imlib2. Losing the ability to look like a weirdo in public transit is a minor inconvenience (I hold the laptop with one hand almost over my head), but it's probably not a big deal. If it is, I can always build the old version specifically for the purpose.
