### ISSUE TITLE
receive commands from the terminal that started feh

### ISSUE THREAD

**Issue by tinus** [derf/feh#67]
I am running feh on a remote machine by starting it from a ssh terminal. I expected to be able to use the shortcuts in the terminal  just as I would when feh is running localy. Feh does output to the terminal (e.g. when a filetype isn't supported) but it doesn't react to input from the terminal. Apparently I can use SIGUSR1 and SIGUSR2 to go back and forth between images but it would be much easier if feh would just react to keyboard input from the terminal.

**Comment by kalsan** [comment]
Lovely hack, @antofthy :-)

**Comment by antofthy** [comment]
Thanks.  Are you making some use of it?

**Comment by kalsan** [comment]
Almost did, then we discovered geeqie which is more suitable for the task.
Using geeqie -r (Filename) you can start a daemonized version of the image viewer (this command must be run from a graphical environment though).
Now geeqie -r -n can switch to the next image and -b goes back. -q causes program exit.
Still, this only seems to work if you can run this initial command from GUI (not from SSH). Luckily we do have this possibility. If that's not possible, I'd fallback to your hack.

**Comment by antofthy** [comment]
Shame its not documented in the man page!  Makes it very hard to learn what
you can do with a application, which is why I missed it.
I would probably also include the "-t" flag to hide the tools.  Hmmm...

My final summary, after having look...

Geeqie provides some controls designed with simple slideshows in mind
rather than more complex scripted interfaces.

The display can be set to/from fullscreen mode, non-fullscreen mode can not
be set to image size or even to some command defined geometry (such as in
display setup).

The window is also automatically brought to the top of the display stack
when a remote command is given (not good, unless full screen, other tools
can do this if it is wanted).

This slideshow remote control is a lot simpler than "feh", however "feh"
also provides some initial window geometry control, and minor feedback
capability.

(now uploaded to my Image Remote Control doc)

---
You can still run it via SSH.

X displays need two things:  the DISPLAY saying where to display and
Permission (typicaly via xauth and XAUTHORITY).

If you want it in the display of the machine you run the command on set
DISPLAY to ":0" and locate the xauth file.  May need root permissions if
you did not start the display yourself.

If you want it on the DISPLAY you launched the ssh command on, the use  ssh
-x to ask it to set up the DISPLAY link.  The remote machine daemon needs
to also accept the X connection, but ssh will tell you if that happens.

**Comment by derf** [comment]
fwiw, receiving commands from the terminal that started feh is supported as of feh 2.20

**Comment by antofthy** [comment]
Thanks Danial.  saw the update when you closed the feh report.
I'll have to investigate further.
