### ISSUE TITLE
toggle_fullscreen action assigned to mouse button not working

### ISSUE THREAD

**Issue by rolandas** [derf/feh#78]
Is it possible to assign keys actions to mouse buttons? Installed newest source, compiled on Fedora 14, tried toggle_fullscreen 1 in mouse configuration, disables keyboard v key and no actions for mouse button. Urgent feature for touchscreen implementations to configure all key actions for 1st and 3rd mouse buttons.

**Comment by alaricljs** [comment]
I'd like to bump this request specifically for action_*

I'm actually using feh and ImageMagick as a calendar applet.  It displays the months calendar and I use feh actions for prev/next month and year and reset to today.  It would be more convenient to use the mouse rather than kb and I was actually surprised that feh complained when I built the config assuming it would work.

Thanks!

**Comment by derf** [comment]
Support for with was added in fd898918df37440fd1c560b8c45aa46523f856b8 and will be included in the next release
